######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 10 23:48:57 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ctmessenger.h newmessage.h
SOURCES += ctmessenger.cpp main.cpp newmessage.cpp
