######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 11 12:18:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += ctmessenger.h newmessage.h
SOURCES += ctmessenger.cpp main.cpp newmessage.cpp
